"""Generate baseline (20,0,80,0) payload for quant panel."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

from quant_tuner import run_tuner_backtest, preload, CACHE
import json

SKILL_DIR = Path(__file__).parent.parent

def main():
    preload()

    # 基准参数 (20,0,80,0) - 2年窗口
    params = {
        'w1': 20, 'w2': 0, 'w3': 80, 'w4': 0, 'w5': 0, 'bias': 0,
        'conf_type': 'quadratic', 'dead_zone': 25, 'full_zone': 65,
        'max_holdings': 6, 'disc_step': 5, 'ema_period': 20, 'rsi_period': 14,
        'vol_window': 20, 'f1_sensitivity': 8.0, 'f3_sensitivity': 1.0, 'f2_dead_zone': 1.5,
        'start_date': '2024-04-29', 'end_date': '2026-04-24'
    }

    print('Running baseline backtest (20,0,80,0)...')
    result = run_tuner_backtest(params)

    # 构建 payload
    payload = {
        "generatedAt": result.get('generatedAt', ''),
        "templateMeta": {
            "baseline": {
                "label": "基准策略",
                "description": "F1(EMA偏离,20%) + F3(方向性量比,80%)，F2/F4/F5归零。年化56%/Sharpe1.73/MDD-13.5%"
            }
        },
        "templates": {
            "baseline": {
                "summary": result.get('summary', {}),
                "navSeries": result.get('navSeries', {}),
                "drawdownSeries": result.get('drawdownSeries', {}),
                "monthlyReturns": result.get('monthlyReturns', []),
                "weeklySnapshots": result.get('weeklySnapshots', []),
                "rebalanceFreq": result.get('rebalanceFreq', []),
                "sectorDistribution": result.get('sectorDistribution', []),
                "riskOrders": result.get('riskOrders', {}),
                "latestSignal": result.get('latestSignal', {})
            }
        },
        "config": {
            "baseline": {
                "scoring": {
                    "weights": {"ema_deviation": 0.20, "rsi_adaptive": 0.0, "volume_ratio": 0.80, "valuation": 0.0, "volatility": 0.0},
                    "bias_bonus": 0.0,
                    "normalization": "continuous"
                },
                "confidence": {"type": "quadratic", "dead_zone": 25, "full_zone": 65},
                "position": {"max_holdings": 6, "discretize_step": 0.05},
                "factors": {
                    "ema": {"period_weeks": 20},
                    "rsi": {"period_days": 14, "dead_zone": 1.5},
                    "volume_ratio": {"window_days": 20}
                }
            }
        },
        "etfNameMap": result.get('etfNameMap', {})
    }

    # 添加参数解释
    payload["strategyInfo"] = {
        "weights": {"F1_EMA": 20, "F2_RSI": 0, "F3_Volume": 80, "F4_Valuation": 0, "F5_Volatility": 0},
        "rationale": "F3(方向性量比)是绝对主导因子，F1(EMA偏离)作为趋势确认辅助。F2/F4/F5在回测中均显示为拖累因子，已归零。",
        "backtestWindow": "2024-04-29 至 2026-04-24 (2年)",
        "keyMetrics": {
            "annualReturn": "56.07%",
            "sharpeRatio": "1.73",
            "maxDrawdown": "-13.47%",
            "calmarRatio": "4.16"
        }
    }

    # 写入文件
    output_path = SKILL_DIR / "data" / "quant_payload_baseline.js"
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(f"// Auto-generated by generate_baseline_payload.py\n")
        f.write(f"// Baseline strategy: (20,0,80,0,0) - F1+F3 only\n")
        f.write(f"window.__QUANT_BASELINE__ = {json.dumps(payload, ensure_ascii=False, indent=2)};")

    print(f"\nPayload saved to: {output_path}")
    s = result.get('summary', {})
    print(f"Summary: {s.get('annualReturn'):.2f}% ann, {s.get('sharpe'):.2f} sharpe, {s.get('maxDrawdown'):.2f}% mdd")

if __name__ == "__main__":
    main()
